var imgArray = new Array();

imgArray[0] = new Image();
imgArray[0].src = 'img/ane.jpg';
document.getElementById('mosaique').appendChild(imgArray[0]);
imgArray[1] = new Image();
imgArray[1].src = 'img/chat.jpg';
document.getElementById('mosaique').appendChild(imgArray[1]);
imgArray[2] = new Image();
imgArray[2].src = 'img/chien.jpg';
document.getElementById('mosaique').appendChild(imgArray[2]);
imgArray[3] = new Image();
imgArray[3].src = 'img/lama.jpg';
document.getElementById('mosaique').appendChild(imgArray[3]);
imgArray[4] = new Image();
imgArray[4].src = 'img/lapins.jpg';
document.getElementById('mosaique').appendChild(imgArray[4]);
imgArray[5] = new Image();
imgArray[5].src = 'img/lionne.jpg';
document.getElementById('mosaique').appendChild(imgArray[5]);
imgArray[6] = new Image();
imgArray[6].src = 'img/ours.jpg';
document.getElementById('mosaique').appendChild(imgArray[6]);
imgArray[0] = new Image();
imgArray[0].src = 'img/ane.jpg';
document.getElementById('mosaique2').appendChild(imgArray[0]);
imgArray[1] = new Image();
imgArray[1].src = 'img/chat.jpg';
document.getElementById('mosaique2').appendChild(imgArray[1]);
imgArray[2] = new Image();
imgArray[2].src = 'img/chien.jpg';
document.getElementById('mosaique2').appendChild(imgArray[2]);
imgArray[3] = new Image();
imgArray[3].src = 'img/lama.jpg';
document.getElementById('mosaique2').appendChild(imgArray[3]);
imgArray[4] = new Image();
imgArray[4].src = 'img/lapins.jpg';
document.getElementById('mosaique2').appendChild(imgArray[4]);
imgArray[5] = new Image();
imgArray[5].src = 'img/lionne.jpg';
document.getElementById('mosaique2').appendChild(imgArray[5]);
imgArray[6] = new Image();
imgArray[6].src = 'img/ours.jpg';
document.getElementById('mosaique2').appendChild(imgArray[6]);

